language: minimal # Includes Docker

services:
  - docker

before_install:
  - docker build -f services/frontend/Dockerfile -t dgp1130/chatter-frontend-test . --target test
  - docker build -f services/rooms/Dockerfile -t dgp1130/chatter-rooms-test . --target test

script:
  - docker run --rm -it -t dgp1130/chatter-frontend-test
  - docker run --rm -it -t dgp1130/chatter-rooms-test
