services:
  - docker

before_install:
  - docker build -t dgp1130/chatter-client-test . --target client-test
  - docker build -t dgp1130/chatter-server-test . --target server-test

script:
  - docker run --rm -it dgp1130/chatter-client-test
  - docker run --rm -it dgp1130/chatter-server-test
