# Chatter service.
apiVersion: v1
kind: Service
metadata:
  name: chatter
  labels:
    app: chatter
spec:
  type: LoadBalancer
  loadBalancerIP: "35.230.3.243"
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: chatter

---

# Service deployment.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatter
  labels:
    app: chatter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatter
  template:
    metadata:
      labels:
        app: chatter
    spec:
      containers:
      - name: chatter
        image: dgp1130/chatter:latest
        ports:
        - containerPort: 80