version: '3.6'

services:
    # Run service for local development.
    dev:
        container_name: chatter-ng-frontend
        build:
            context: .
            target: dev
        volumes:
            # Bind source code for live reload when source files are edited.
            - '.:/chatter/services/ng-frontend/'
            # Bind anonymous volume at node_modules/ so it uses the version built by Docker, rather
            # than the host version of dependencies.
            - '/chatter/services/ng-frontend/node_modules/'
        ports:
            - '4200:4200'
