version: '3.6'

services:
    # Run service for local development.
    dev:
        container_name: chatter-ng-frontend-dev
        build:
            context: .
            target: dev
        volumes:
            # Bind source code for live reload when source files are edited.
            - '.:/chatter/services/ng-frontend/'
            # Bind anonymous volume at node_modules/ so it uses the version built by Docker, rather
            # than the host version of dependencies.
            - '/chatter/services/ng-frontend/node_modules/'
        ports:
            - '4200:4200'

    # Run production server.
    prod:
        container_name: chatter-ng-frontend-prod
        build:
            context: .
            target: prod
        ports:
            - '8000:80'

    # Run unit tests (not e2e).
    test:
        container_name: chatter-ng-frontend-test
        build:
            context: .
            target: test

    # Debug unit tests (not e2e) locally.
    test-debug:
        container_name: chatter-ng-frontend-test-debug
        build:
            context: .
            target: test-debug
        volumes:
            # Bind source code for live reload when source files are edited.
            - '.:/chatter/services/ng-frontend/'
            # Bind anonymous volume at node_modules/ so it uses the version built by Docker, rather
            # than the host version of dependencies.
            - '/chatter/services/ng-frontend/node_modules/'
        ports:
            - '9876:9876'

    # Run end-to-end tests.
    e2e:
        container_name: chatter-ng-frontend-e2e
        build:
            context: .
            target: e2e
