name: Docker Publish Rooms Service

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -f services/rooms/Dockerfile -t dgp1130/chatter-rooms-service:latest --target server services/rooms

  login:
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  publish:
    runs-on: ubuntu-latest
    needs: 
    - build
    - login
    steps:
    - name: Publish
      run: docker push dgp1130/chatter-rooms-service:latest
